### ISSUE TITLE
maintaining?

### ISSUE THREAD

**Issue by yocontra** [nulltask/stable-timer#5]
are you planning on maintaining this? do you need a maintainer?

we are using this and there are multiple critical bugs open (which we already sent PRs to fix). we are going to publish our fork as its own module if you are going to abandon this repo

**Comment by nulltask** [comment]
I want to maintain this library, but I don't have enough time for that. I can add you to repo and npm registry, if you want to maintain this and its several dependencies.

**Comment by yocontra** [comment]
@nulltask Yep! I will maintain it + the dependencies

npm username is `fractal`

**Comment by nulltask** [comment]
I've just added you to repo and registry. Please feel free to commit and publish under semantic versioning.
